# Generated by Django 4.2 on 2023-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары на складе'},
        ),
    ]
