# Generated by Django 4.2 on 2023-05-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stocks_alter_items_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(verbose_name='Индентификатор клиента')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientsOrders',
            fields=[
                ('client_id', models.ManyToManyField(to='main.clients')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('vendor_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.items')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Количество товара',
                'verbose_name_plural': 'Количество товаров',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
        migrations.AddField(
            model_name='clientsorders',
            name='id',
            field=models.ManyToManyField(to='main.orders'),
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.orders')),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.items')),
            ],
            options={
                'verbose_name': 'Содержание заказа',
                'verbose_name_plural': 'Содержание заказов',
            },
        ),
    ]
